"""empty message

Revision ID: 0b7e5b749209
Revises: c5a4394d1b4a
Create Date: 2020-05-05 15:32:06.523212

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b7e5b749209'
down_revision = 'c5a4394d1b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('public', sa.Boolean(), nullable=False))
    op.add_column('sets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('sets', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_foreign_key(None, 'sets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sets', type_='foreignkey')
    op.alter_column('sets', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('sets', 'user_id')
    op.drop_column('sets', 'public')
    # ### end Alembic commands ###
