"""empty message

Revision ID: 1ceefb229521
Revises: 
Create Date: 2020-05-05 21:11:56.502751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ceefb229521'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sets',
    sa.Column('set_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('set_id')
    )
    op.create_table('cards',
    sa.Column('card_ID', sa.INTEGER(), nullable=False),
    sa.Column('set_id', sa.INTEGER(), nullable=False),
    sa.Column('card_order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['sets.set_id'], ),
    sa.PrimaryKeyConstraint('card_ID')
    )
    op.create_index(op.f('ix_cards_set_id'), 'cards', ['set_id'], unique=False)
    op.create_table('sides',
    sa.Column('side_id', sa.INTEGER(), nullable=False),
    sa.Column('set_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('side_order', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['set_id'], ['sets.set_id'], ),
    sa.PrimaryKeyConstraint('side_id')
    )
    op.create_index(op.f('ix_sides_set_id'), 'sides', ['set_id'], unique=False)
    op.create_table('cells',
    sa.Column('cell_id', sa.INTEGER(), nullable=False),
    sa.Column('card_id', sa.INTEGER(), nullable=False),
    sa.Column('side_id', sa.INTEGER(), nullable=False),
    sa.Column('info', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.card_ID'], ),
    sa.ForeignKeyConstraint(['side_id'], ['sides.side_id'], ),
    sa.PrimaryKeyConstraint('cell_id')
    )
    op.create_index(op.f('ix_cells_card_id'), 'cells', ['card_id'], unique=False)
    op.create_index(op.f('ix_cells_side_id'), 'cells', ['side_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cells_side_id'), table_name='cells')
    op.drop_index(op.f('ix_cells_card_id'), table_name='cells')
    op.drop_table('cells')
    op.drop_index(op.f('ix_sides_set_id'), table_name='sides')
    op.drop_table('sides')
    op.drop_index(op.f('ix_cards_set_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_table('sets')
    op.drop_table('users')
    # ### end Alembic commands ###
