"""empty message

Revision ID: 7706e568b38b
Revises: 1ceefb229521
Create Date: 2020-05-06 12:14:51.061644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7706e568b38b'
down_revision = '1ceefb229521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
