"""empty message

Revision ID: c5a4394d1b4a
Revises: 
Create Date: 2020-05-04 17:22:18.244549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5a4394d1b4a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_cards_set_id'), 'cards', ['set_id'], unique=False)
    op.create_index(op.f('ix_cells_card_id'), 'cells', ['card_id'], unique=False)
    op.create_index(op.f('ix_cells_side_id'), 'cells', ['side_id'], unique=False)
    op.create_index(op.f('ix_sides_set_id'), 'sides', ['set_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sides_set_id'), table_name='sides')
    op.drop_index(op.f('ix_cells_side_id'), table_name='cells')
    op.drop_index(op.f('ix_cells_card_id'), table_name='cells')
    op.drop_index(op.f('ix_cards_set_id'), table_name='cards')
    op.drop_table('users')
    # ### end Alembic commands ###
